# Generated by Django 5.2.6 on 2025-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='consecutive',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='consecutive_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
