# Generated by Django 5.2.6 on 2025-09-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_alter_clients_created_at_alter_clients_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.BooleanField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
    ]
