# Generated by Django 5.2.6 on 2025-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_alter_clients_status_alter_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='taxes',
            field=models.BooleanField(choices=[(1, 'Con IVA'), (0, 'Sin IVA')], default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='value_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
