# Generated by Django 5.2.6 on 2025-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_managestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managestock',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Salida'), (3, 'Transferencia')], default=1),
        ),
    ]
